### ISSUE TITLE
object has no attribute 'virtual_chassis'

### ISSUE THREAD

**Issue by Kimotu** [peterbaumert/netbox-device-view#44]
I wanted to try your plugin. Seems not to work with netbox 4.3.1 yet.

Several objects throws an error:
- site
- rack
- racktype
- region
- ...

```<class 'AttributeError'>

'Rack' object has no attribute 'virtual_chassis'

Python version: 3.12.3
NetBox version: 4.3.1
Plugins: 
  netbox_device_view: 0.1.9
  netbox_dns: 1.3.1
  netbox_floorplan: 0.7.0```

**Comment by fzs** [comment]
I second that.

```
<class 'AttributeError'>

'Location' object has no attribute 'virtual_chassis'

Python version: 3.11.2
NetBox version: 4.3.1
Plugins: 
  netbox_device_view: 0.1.9
  netbox_floorplan: 0.7.0
  netbox_topology_views: 4.3.0
```

This only happens when activating the `show_on_device_tab` plugin option.

The object is created, but this error occurs.
